server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群


# 注意: 消费者端一直是有兜底方法的,所以这里feign.hystrix.enabled不用配置,配置后如果有超时会直接走兜底方法,也不太明白为啥
#feign:
#  hystrix:
#    enabled: true #开启fengn


#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #  指的是建立连接后从服务器取读到可用资源所用的时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间,适用于网络状况正常的情况下,两端连接用的时间
  ConnectTimeout: 5000
